name: connect4 # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Connect 4 # 79 char long summary
description: |
  Play the game Connect 4 on your command-line
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  connect4:
    # See 'snapcraft plugins'
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six
    
apps:
  connect4:
    command: bin/connect4
